# Theme based on https://github.com/pages-themes/hacker

title: Maupin Radio
email: info@maupinradio.org
description: maupinradio.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown